IMPORTING DPENDENCIES

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))




import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns


from ETL.ETL_PIPELINE import  ETL
from PROCESSING.DATA_PROCESSING import DataProcessor
from UTILS.data_path import get_data_path

In [3]:

#CLASSIFICATION MEASURMENTS
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    balanced_accuracy_score,
    average_precision_score,
    roc_auc_score
)

#pipeline

from sklearn.pipeline import Pipeline

#preprocessing

from sklearn.preprocessing import StandardScaler

#CLASSIFICATION ALGORITHMS

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC



from sklearn.ensemble import(

    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    BaggingClassifier
    
  )


#Model_Selection Classes

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV,
    RandomizedSearchCV                        
    )

#IMPUTTER

from sklearn.impute import SimpleImputer


from xgboost import XGBClassifier

from sklearn.discriminant_analysis import (
    LinearDiscriminantAnalysis,
    QuadraticDiscriminantAnalysis
)

from sklearn.naive_bayes import GaussianNB

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [15]:
from scipy.stats import (
    randint,
    loguniform,
    uniform
)

In [3]:
path = get_data_path()
print(path)

c:\Users\IGO\OneDrive\Bureau\WATER\DATASET\water_potability.csv

In [6]:
path = get_data_path()


df = ETL.run(path)

df.head()

[OK] Column validation passed.
[OK] Data type validation passed.
[OK] Dataset validation successful.
======================================================================
                 DATASET INSPECTION REPORT
======================================================================

GENERAL INFORMATION
----------------------------------------------------------------------
Dimensions             : (3276, 10)
Rows                   : 3,276
Columns                : 10
Duplicate Rows         : 0
Duplicate Rows (%)     : 0.00%

COLUMN INFORMATION
----------------------------------------------------------------------
                Data Type  Non-Missing  Missing  Missing %  Duplicate Values %  Duplicated Column
chloramines       float64         3276        0       0.00                0.00              False
conductivity      float64         3276        0       0.00                0.00              False
hardness          float64         3276        0       0.00                0.00              False
organic_carbon    float64         3276        0       0.00                0.00              False
ph                float64         2785      491      14.99               14.96              False
potability          int64         3276        0       0.00               99.94              False
solids            float64         3276        0       0.00                0.00              False
sulfate           float64         2495      781      23.84               23.81              False
trihalomethanes   float64         3114      162       4.95                4.91              False
turbidity         float64         3276        0       0.00                0.00              False

SAMPLE OF THE DATASET
----------------------------------------------------------------------

First 5 rows:
         ph    hardness        solids  chloramines     sulfate  conductivity  organic_carbon  trihalomethanes  turbidity  potability
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654       10.379783        86.990970   2.963135           0
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359       15.180013        56.329076   4.500656           0
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213       16.868637        66.420093   3.055934           0
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516       18.436524       100.341674   4.628771           0
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813       11.558279        31.997993   4.075075           0

Last 5 rows:
            ph    hardness        solids  chloramines     sulfate  conductivity  organic_carbon  trihalomethanes  turbidity  potability
3271  4.668102  193.681735  47580.991603     7.166639  359.948574    526.424171       13.894419        66.687695   4.435821           1
3272  7.808856  193.553212  17329.802160     8.061362         NaN    392.449580       19.903225              NaN   2.798243           1
3273  9.419510  175.762646  33155.578218     7.350233         NaN    432.044783       11.039070        69.845400   3.298875           1
3274  5.126763  230.603758  11983.869376     6.303357         NaN    402.883113       11.168946        77.488213   4.708658           1
3275  7.874671  195.102299  17404.177061     7.509306         NaN    327.459760       16.140368        78.698446   2.309149           1

STATISTICAL SUMMARY
----------------------------------------------------------------------
                ph     hardness        solids  chloramines      sulfate  conductivity  organic_carbon  trihalomethanes    turbidity   potability
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000
mean      7.080795   196.369496  22014.092526     7.122277   333.775777    426.205111       14.284970        66.396293     3.966786     0.390110
std       1.594320    32.879761   8768.570828     1.583085    41.416840     80.824064        3.308162        16.175008     0.780382     0.487849
min       0.000000    47.432000    320.942611     0.352000   129.000000    181.483754        2.200000         0.738000     1.450000     0.000000
25%       6.093092   176.850538  15666.690297     6.127421   307.699498    365.734414       12.065801        55.844536     3.439711     0.000000
50%       7.036752   196.967627  20927.833607     7.130299   333.073546    421.884968       14.218338        66.622485     3.955028     0.000000
75%       8.062066   216.667456  27332.762127     8.114887   359.950170    481.792304       16.557652        77.337473     4.500320     1.000000
max      14.000000   323.124000  61227.196008    13.127000   481.030642    753.342620       28.300000       124.000000     6.739000     1.000000

======================================================================
                  END OF REPORT
======================================================================

,ph,hardness,solids,chloramines,sulfate,conductivity,organic_carbon,trihalomethanes,turbidity,potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

CREATING A CLASS PROTOTYPE FOR DATA PREPROCESSING

In [1]:
""""
class DataProcessor:

    def __init__(
        self,
        data: pd.DataFrame,
        target_col: str = "potability",
        test_size: float = 0.2,
        random_state: int = 42
    ):
        if not isinstance(data, pd.DataFrame):
            raise TypeError("data must be a pandas DataFrame")

        if target_col not in data.columns:
            raise ValueError(
                f"Target column '{target_col}' was not found in the DataFrame."
            )

        if data[target_col].isna().any():
            raise ValueError(
                f"Target column '{target_col}' contains missing values."
            )

        self.df = data.copy()
        self.target_col = target_col
        self.test_size = test_size
        self.random_state = random_state

        self.preprocessor = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])




    def process(self):

        # --------------------------------------------------
        # 1. Separate features and target
        # --------------------------------------------------

        X = self.df.drop(columns=self.target_col)
        y = self.df[self.target_col]

        # Keep feature names for the final DataFrames
        feature_names = X.columns.tolist()

        # --------------------------------------------------
        # 2. Split the data
        # --------------------------------------------------

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=self.test_size,
            random_state=self.random_state,
            stratify=y
        )

        # Save indexes so they remain aligned after transformation
        train_index = X_train.index
        test_index = X_test.index

        # --------------------------------------------------
        # 3. Fit preprocessing ONLY on training data
        # --------------------------------------------------

        X_train = self.preprocessor.fit_transform(X_train)

        # --------------------------------------------------
        # 4. Apply learned preprocessing to test data
        # --------------------------------------------------

        X_test = self.preprocessor.transform(X_test)

        # --------------------------------------------------
        # 5. Convert transformed arrays back to DataFrames
        # --------------------------------------------------

        X_train_df = pd.DataFrame(
            X_train,
            columns=feature_names,
            index=train_index
        )

        X_test_df = pd.DataFrame(
            X_test,
            columns=feature_names,
            index=test_index
        )

        # --------------------------------------------------
        # 6. Keep targets as Series
        # --------------------------------------------------

        y_train = y_train.rename(self.target_col)
        y_test = y_test.rename(self.target_col)

        # --------------------------------------------------
        # 7. Return processed data
        # --------------------------------------------------

        return X_train_df, X_test_df, y_train, y_test

"""

'"\nclass DataProcessor:\n\n    def __init__(\n        self,\n        data: pd.DataFrame,\n        target_col: str = "potability",\n        test_size: float = 0.2,\n        random_state: int = 42\n    ):\n        if not isinstance(data, pd.DataFrame):\n            raise TypeError("data must be a pandas DataFrame")\n\n        if target_col not in data.columns:\n            raise ValueError(\n                f"Target column \'{target_col}\' was not found in the DataFrame."\n            )\n\n        if data[target_col].isna().any():\n            raise ValueError(\n                f"Target column \'{target_col}\' contains missing values."\n            )\n\n        self.df = data.copy()\n        self.target_col = target_col\n        self.test_size = test_size\n        self.random_state = random_state\n\n        self.preprocessor = Pipeline([\n            ("imputer", SimpleImputer(strategy="median")),\n            ("scaler", StandardScaler())\n        ])\n\n\n\n\n    def process(self):\n\n        # --------------------------------------------------\n        # 1. Separate features and target\n        # --------------------------------------------------\n\n        X = self.df.drop(columns=self.target_col)\n        y = self.df[self.target_col]\n\n        # Keep feature names for the final DataFrames\n        feature_names = X.columns.tolist()\n\n        # --------------------------------------------------\n        # 2. Split the data\n        # --------------------------------------------------\n\n        X_train, X_test, y_train, y_test = train_test_split(\n            X,\n            y,\n            test_size=self.test_size,\n            random_state=self.random_state,\n            stratify=y\n        )\n\n        # Save indexes so they remain aligned after transformation\n        train_index = X_train.index\n        test_index = X_test.index\n\n        # --------------------------------------------------\n        # 3. Fit preprocessing ONLY on training data\n        # --------------------------------------------------\n\n        X_train = self.preprocessor.fit_transform(X_train)\n\n        # --------------------------------------------------\n        # 4. Apply learned preprocessing to test data\n        # --------------------------------------------------\n\n        X_test = self.preprocessor.transform(X_test)\n\n        # --------------------------------------------------\n        # 5. Convert transformed arrays back to DataFrames\n        # --------------------------------------------------\n\n        X_train_df = pd.DataFrame(\n            X_train,\n            columns=feature_names,\n            index=train_index\n        )\n\n        X_test_df = pd.DataFrame(\n            X_test,\n            columns=feature_names,\n            index=test_index\n        )\n\n        # --------------------------------------------------\n        # 6. Keep targets as Series\n        # --------------------------------------------------\n\n        y_train = y_train.rename(self.target_col)\n        y_test = y_test.rename(self.target_col)\n\n        # --------------------------------------------------\n        # 7. Return processed data\n        # --------------------------------------------------\n\n        return X_train_df, X_test_df, y_train, y_test\n\n'

CREATING MACHINE LEARNING MODELS

In [ ]:
print("here the models training")

here the models training

PROTOTYPE MODELS PARAMETERS FOR HYPERPARAMETER TUNING

In [ ]:
#LOGISTIC REGRESSION

logistic_regression_par = [

    # L2 penalty
    {
        "C": [0.001, 0.005, 0.01, 0.1, 0.5, 1, 5, 10],
        "max_iter": [500, 1000, 2000],
        "penalty": ["l2"],
        "solver": [
            "lbfgs",
            "liblinear",
            "newton-cg",
            "newton-cholesky",
            "sag",
            "saga"
        ],
        "fit_intercept": [True, False],
        "class_weight": [None, "balanced"]
    },

    # L1 penalty
    {
        "C": [0.001, 0.005, 0.01, 0.1, 0.5, 1, 5, 10],
        "max_iter": [500, 1000, 2000],
        "penalty": ["l1"],
        "solver": [
            "liblinear",
            "saga"
        ],
        "fit_intercept": [True, False],
        "class_weight": [None, "balanced"]
    },

    # No regularization
    {
        "max_iter": [500, 1000, 2000],
        "penalty": [None],
        "solver": [
            "lbfgs",
            "newton-cg",
            "newton-cholesky",
            "sag",
            "saga"
        ],
        "fit_intercept": [True, False],
        "class_weight": [None, "balanced"]
    },

    # Elastic Net
    {
        "C": [0.001, 0.005, 0.01, 0.1, 0.5, 1, 5, 10],
        "max_iter": [500, 1000, 2000],
        "penalty": ["elasticnet"],
        "solver": ["saga"],
        "l1_ratio": [0.1, 0.5, 0.9],
        "fit_intercept": [True, False],
        "class_weight": [None, "balanced"]
    }
]



#Decision_Tree


Decision_Tree_params = {

    "criterion": ["gini", "entropy", "log_loss"],

    "splitter": ["best", "random"],

    "max_depth": [None, 5, 10, 15, 20, 30],

    "min_samples_split": [2, 5, 10, 15, 20],

    "min_samples_leaf": [1, 2, 4, 6, 10],

    "max_features": ["sqrt", "log2", None],

    "max_leaf_nodes": [None, 10, 20, 40, 80],

    "class_weight": [None, "balanced"],

    "ccp_alpha": [0.0, 0.0001, 0.001, 0.01]
}




#Random Forest

Random_Forest_Classifier_params = {

    # Number of trees in the forest
    "n_estimators": randint(200, 801),

    # Maximum depth of each tree
    "max_depth": [
        None,
        5,
        10,
        15,
        20,
        30
    ],

    # Minimum samples required to split a node
    "min_samples_split": randint(2, 21),

    # Minimum samples required in a leaf
    "min_samples_leaf": randint(1, 11),

    # Split criterion
    "criterion": [
        "gini",
        "entropy",
        "log_loss"
    ],

    # Number of features considered at each split
    "max_features": [
        "sqrt",
        "log2",
        None
    ],

    # Maximum number of leaf nodes
    "max_leaf_nodes": [
        None,
        10,
        20,
        40,
        80
    ],

    # Handling class imbalance
    "class_weight": [
        None,
        "balanced",
        "balanced_subsample"
    ],

    # Cost-complexity pruning
    "ccp_alpha": [
        0.0,
        0.00001,
        0.0001,
        0.001,
        0.01
    ]
}



#Gradient Boosting Classifier

param_grid = {
    "n_estimators": [50, 100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "max_depth": [1, 2, 3, 4, 5],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5, 10],
    "subsample": [0.7, 0.8, 1.0],
    "max_features": [None, "sqrt", "log2"]
}




#KNN

KNN_params = {

    # Number of neighbors
    "n_neighbors": randint(3, 31),

    # How neighbors are weighted
    "weights": [
        "uniform",
        "distance"
    ],

    # Distance metric
    "metric": [
        "euclidean",
        "manhattan",
        "minkowski"
    ],

    # Power parameter for Minkowski distance
    "p": [1, 2],

    # Algorithm used to find neighbors
    "algorithm": [
        "auto",
        "ball_tree",
        "kd_tree",
        "brute"
    ],

    # Leaf size used by tree-based algorithms
    "leaf_size": [
        10,
        20,
        30,
        40,
        50
    ]
}




#SVM


SVM_params = {

    # Regularization
    "C": loguniform(0.01, 100),

    # Kernel function
    "kernel": [
        "linear",
        "rbf",
        "poly",
        "sigmoid"
    ],

    # Kernel coefficient
    "gamma": [
        "scale",
        "auto"
    ],

    # Polynomial degree
    "degree": [2, 3, 4, 5],

    # Independent term for poly/sigmoid
    "coef0": [0.0, 0.1, 0.5, 1.0],

    # Class imbalance
    "class_weight": [
        None,
        "balanced"
    ]
}




#XGBoost Classifier


XGBoost_params = {

    # Number of boosting rounds / trees
    "n_estimators": randint(100, 801),

    # Step size of each boosting round
    "learning_rate": loguniform(0.01, 0.3),

    # Maximum depth of each tree
    "max_depth": randint(2, 11),

    # Minimum sum of instance weight needed in a child
    "min_child_weight": randint(1, 11),

    # Minimum loss reduction required for a split
    "gamma": [0, 0.01, 0.1, 0.3, 0.5, 1, 2, 5],

    # Fraction of training rows used for each tree
    "subsample": uniform(0.6, 0.4),

    # Fraction of features used for each tree
    "colsample_bytree": uniform(0.6, 0.4),

    # L1 regularization
    "reg_alpha": loguniform(1e-4, 10),

    # L2 regularization
    "reg_lambda": loguniform(1e-3, 100),

    # Class imbalance
    "scale_pos_weight": [1, 1.5, 2, 3]
}

CREATING A CLASS PROTOTYPE FOR HYPER-PARAMETER TUNNING

In [ ]:

""""

V1

class HyperparameterTuner:

    def __init__(
        self,
        model,
        param_grid,
        scoring="f1",
        cv=5,
        random_state=42,
        n_jobs=-1
    ):
        self.model = model
        self.param_grid = param_grid
        self.scoring = scoring
        self.cv = cv
        self.random_state = random_state
        self.n_jobs = n_jobs



        def checker(model):

            simple_models = (
                LogisticRegression,
                SVC,
                KNeighborsClassifier
            )

            complex_models = (
                DecisionTreeClassifier,
                RandomForestClassifier,
                GradientBoostingClassifier,
                AdaBoostClassifier,
                BaggingClassifier
            )

            if isinstance(model, simple_models):
                return "simple"

            if isinstance(model, complex_models):
                return "complex"

            return "unknown"

        





        def tune(self, X_train, y_train):

                cv_strategy = StratifiedKFold(
                    n_splits=self.cv,
                    shuffle=True,
                    random_state=self.random_state
                )


                model_type = checker(self.model)



                if model_type == "simple":
            
                    print("The model is simple.")

                    search = GridSearchCV(
                                estimator=self.model,
                                param_grid=self.param_grid,
                                cv=cv_strategy,
                                scoring=self.scoring,
                                n_jobs=self.n_jobs,
                                refit=True
                            )
                    search.fit(X_train, y_train)
                    return search.best_params_




                elif model_type == "complex":

                    print("The model is complex.")

                    random_search = RandomizedSearchCV(
                    estimator=self.model,
                    param_distributions=self.param_grid,
                    n_iter=20,
                    scoring="f1",
                    cv=5,
                    random_state=42,
                    n_jobs=-1
                        )


                    random_search.fit(X_train, y_train)
                    return random_search.best_params_



                else:
                    print("The model type is unknown.")   
                    raise ValueError(
                                     f"Unsupported model type: {type(self.model).__name__}"
)



""""

In [ ]:

class HyperparameterTuner:

    def __init__(
        self,
        model,
        search_space,
        search_type="grid",
        cv=5,
        scoring={
                "accuracy": "accuracy",
                "precision": "precision",
                "recall": "recall",
                "f1": "f1",
                "roc_auc": "roc_auc"
                },
        n_iter=20,
        n_jobs=-1,
        random_state=42
    ):
        self.model = model
        self.search_space = search_space
        self.search_type = search_type
        self.cv = cv
        self.scoring = scoring
        self.n_iter = n_iter
        self.n_jobs = n_jobs
        self.random_state = random_state


    def tune(self, X_train, y_train):

        cv_strategy = StratifiedKFold(
            n_splits=self.cv,
            shuffle=True,
            random_state=self.random_state
        )

        if self.search_type == "grid":

            search = GridSearchCV(
                estimator=self.model,
                param_grid=self.search_space,
                cv=cv_strategy,
                scoring=self.scoring,
                n_jobs=self.n_jobs,
                refit="f1"
            )

        elif self.search_type == "random":

            search = RandomizedSearchCV(
                estimator=self.model,
                param_distributions=self.search_space,
                n_iter=self.n_iter,
                cv=cv_strategy,
                scoring=self.scoring,
                n_jobs=self.n_jobs,
                random_state=self.random_state,
                refit="f1"
            )

        else:

            raise ValueError(
                f"Unknown search_type: {self.search_type}"
            )

        search.fit(X_train, y_train)

        return {
            "best_params": search.best_params_,
            "best_score": search.best_score_,
            "best_estimator": search.best_estimator_,
            "search_object": search
        }

In [ ]:
processor = DataProcessor(df)

X_train, X_test, y_train, y_test = processor.process()




logistic_tuner = HyperparameterTuner(
    model=LogisticRegression(),
    search_space=logistic_regression_par,
    search_type="grid"

    
)


logistic_tuner.tune(X_train, y_train)

c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

{'best_params': {'C': 0.001,
  'class_weight': 'balanced',
  'fit_intercept': True,
  'l1_ratio': 0.1,
  'max_iter': 500,
  'penalty': 'elasticnet',
  'solver': 'saga'},
 'best_score': np.float64(0.5612294427109242),
 'best_estimator': LogisticRegression(C=0.001, class_weight='balanced', l1_ratio=0.1, max_iter=500,
                    penalty='elasticnet', solver='saga'),
 'search_object': GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
              estimator=LogisticRegression(), n_jobs=-1,
              param_grid=[{'C': [0.001, 0.005, 0.01, 0.1, 0.5, 1, 5, 10],
                           'class_weight': [None, 'balanced'],
                           'fit_intercept': [True, False],
                           'max_iter': [500, 1000, 2000], 'penalty': ['l2'],
                           'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                      'newton-cholesky', 'sag', 'saga']},
                          {'C'...
                          {'class_weight': [None, 'balanced'],
                           'fit_intercept': [True, False],
                           'max_iter': [500, 1000, 2000], 'penalty': [None],
                           'solver': ['lbfgs', 'newton-cg', 'newton-cholesky',
                                      'sag', 'saga']},
                          {'C': [0.001, 0.005, 0.01, 0.1, 0.5, 1, 5, 10],
                           'class_weight': [None, 'balanced'],
                           'fit_intercept': [True, False],
                           'l1_ratio': [0.1, 0.5, 0.9],
                           'max_iter': [500, 1000, 2000],
                           'penalty': ['elasticnet'], 'solver': ['saga']}],
              scoring='f1')}

In [19]:
path = get_data_path()


df = ETL.run(path)

df.head()

[OK] Column validation passed.
[OK] Data type validation passed.
[OK] Dataset validation successful.
======================================================================
                 DATASET INSPECTION REPORT
======================================================================

GENERAL INFORMATION
----------------------------------------------------------------------
Dimensions             : (3276, 10)
Rows                   : 3,276
Columns                : 10
Duplicate Rows         : 0
Duplicate Rows (%)     : 0.00%

COLUMN INFORMATION
----------------------------------------------------------------------
                Data Type  Non-Missing  Missing  Missing %  Duplicate Values %  Duplicated Column
chloramines       float64         3276        0       0.00                0.00              False
conductivity      float64         3276        0       0.00                0.00              False
hardness          float64         3276        0       0.00                0.00              False
organic_carbon    float64         3276        0       0.00                0.00              False
ph                float64         2785      491      14.99               14.96              False
potability          int64         3276        0       0.00               99.94              False
solids            float64         3276        0       0.00                0.00              False
sulfate           float64         2495      781      23.84               23.81              False
trihalomethanes   float64         3114      162       4.95                4.91              False
turbidity         float64         3276        0       0.00                0.00              False

SAMPLE OF THE DATASET
----------------------------------------------------------------------

First 5 rows:
         ph    hardness        solids  chloramines     sulfate  conductivity  organic_carbon  trihalomethanes  turbidity  potability
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654       10.379783        86.990970   2.963135           0
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359       15.180013        56.329076   4.500656           0
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213       16.868637        66.420093   3.055934           0
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516       18.436524       100.341674   4.628771           0
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813       11.558279        31.997993   4.075075           0

Last 5 rows:
            ph    hardness        solids  chloramines     sulfate  conductivity  organic_carbon  trihalomethanes  turbidity  potability
3271  4.668102  193.681735  47580.991603     7.166639  359.948574    526.424171       13.894419        66.687695   4.435821           1
3272  7.808856  193.553212  17329.802160     8.061362         NaN    392.449580       19.903225              NaN   2.798243           1
3273  9.419510  175.762646  33155.578218     7.350233         NaN    432.044783       11.039070        69.845400   3.298875           1
3274  5.126763  230.603758  11983.869376     6.303357         NaN    402.883113       11.168946        77.488213   4.708658           1
3275  7.874671  195.102299  17404.177061     7.509306         NaN    327.459760       16.140368        78.698446   2.309149           1

STATISTICAL SUMMARY
----------------------------------------------------------------------
                ph     hardness        solids  chloramines      sulfate  conductivity  organic_carbon  trihalomethanes    turbidity   potability
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000
mean      7.080795   196.369496  22014.092526     7.122277   333.775777    426.205111       14.284970        66.396293     3.966786     0.390110
std       1.594320    32.879761   8768.570828     1.583085    41.416840     80.824064        3.308162        16.175008     0.780382     0.487849
min       0.000000    47.432000    320.942611     0.352000   129.000000    181.483754        2.200000         0.738000     1.450000     0.000000
25%       6.093092   176.850538  15666.690297     6.127421   307.699498    365.734414       12.065801        55.844536     3.439711     0.000000
50%       7.036752   196.967627  20927.833607     7.130299   333.073546    421.884968       14.218338        66.622485     3.955028     0.000000
75%       8.062066   216.667456  27332.762127     8.114887   359.950170    481.792304       16.557652        77.337473     4.500320     1.000000
max      14.000000   323.124000  61227.196008    13.127000   481.030642    753.342620       28.300000       124.000000     6.739000     1.000000

======================================================================
                  END OF REPORT
======================================================================

,ph,hardness,solids,chloramines,sulfate,conductivity,organic_carbon,trihalomethanes,turbidity,potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [19]:

def simple_test(y_test , y_predict ,y_proba , model_name ):

        

        acc  = round(accuracy_score(y_test, y_predict),3)
        prec = round(precision_score(y_test, y_predict),3)
        rec  = round(recall_score(y_test, y_predict),3)
        f1   = round(f1_score(y_test, y_predict),3)
        auc  = round(roc_auc_score(y_test, y_proba),3)
        balanced_acc = round(balanced_accuracy_score(y_test, y_predict),3)
        pr_auc = round(average_precision_score(y_test, y_proba),3)


       

        return {
        "Model": model_name,
        "Accuracy": round(accuracy_score(y_test, y_predict), 3),
        "Precision": round(precision_score(y_test, y_predict), 3),
        "Recall": round(recall_score(y_test, y_predict), 3),
        "F1": round(f1_score(y_test, y_predict), 3),
        "ROC-AUC": round(roc_auc_score(y_test, y_proba), 3),
        "PR-AUC": round(average_precision_score(y_test, y_proba), 3),
        "Balanced Accuracy": round(
            balanced_accuracy_score(y_test, y_predict), 3
        )
    }







def run_all_models(df,models):

        metrics = []
        processor = DataProcessor(df)
        X_train, X_test, y_train, y_test = processor.process()

        for model_name, model in models.items():
            print(f"Training {model_name}...")
            model.fit(X_train, y_train)
            y_predict = model.predict(X_test)
            y_proba = model.predict_proba(X_test)[:, 1]  # Get probabilities for the positive class

            m=simple_test(y_test, y_predict, y_proba, model_name)


            metrics.append(m)

        return pd.DataFrame(metrics)

In [20]:
models = {
    "Logistic Regression": LogisticRegression(),
    "LDA": LinearDiscriminantAnalysis(),
    "QDA": QuadraticDiscriminantAnalysis(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "XGBoost": XGBClassifier(),
    "LightGBM": LGBMClassifier(),
    "CatBoost": CatBoostClassifier(),
    #"SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}



metrics = run_all_models(df , models)
metrics.head(20)

Training Logistic Regression...
Training LDA...

c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Training QDA...
Training Decision Tree...
Training Random Forest...
Training Gradient Boosting...
Training XGBoost...
Training LightGBM...
[LightGBM] [Info] Number of positive: 1022, number of negative: 1598
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000251 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2295
[LightGBM] [Info] Number of data points in the train set: 2620, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.390076 -> initscore=-0.446991
[LightGBM] [Info] Start training from score -0.446991
Training CatBoost...
Learning rate set to 0.015543
0:	learn: 0.6907566	total: 5.5ms	remaining: 5.5s
1:	learn: 0.6895101	total: 13.5ms	remaining: 6.72s
2:	learn: 0.6878912	total: 19.1ms	remaining: 6.34s
3:	learn: 0.6860822	total: 25.2ms	remaining: 6.26s
4:	learn: 0.6841549	total: 31.5ms	remaining: 6.26s
5:	learn: 0.6827359	total: 37.4ms	remaining: 6.19s
6:	learn: 0.6811870	total: 44.6ms	remaining: 6.33s
7:	learn: 0.6799684	total: 50.4ms	remaining: 6.24s
8:	learn: 0.6784943	total: 56.9ms	remaining: 6.27s
9:	learn: 0.6768095	total: 64.1ms	remaining: 6.35s
10:	learn: 0.6754283	total: 71ms	remaining: 6.38s
11:	learn: 0.6735641	total: 78.8ms	remaining: 6.48s
12:	learn: 0.6721659	total: 84.2ms	remaining: 6.39s
13:	learn: 0.6712741	total: 96.4ms	remaining: 6.79s
14:	learn: 0.6700972	total: 103ms	remaining: 6.75s
15:	learn: 0.6691290	total: 112ms	remaining: 6.87s
16:	learn: 0.6669841	total: 119ms	remaining: 6.86s
17:	learn: 0.6652379	total: 128ms	remaining: 6.96s
18:	learn: 0.6638841	total: 134ms	remaining: 6.91s
19:	learn: 0.6623570	total: 142ms	remaining: 6.97s
20:	learn: 0.6609614	total: 149ms	remaining: 6.95s
21:	learn: 0.6599522	total: 158ms	remaining: 7.03s
22:	learn: 0.6590445	total: 164ms	remaining: 6.95s
23:	learn: 0.6576270	total: 171ms	remaining: 6.94s
24:	learn: 0.6562864	total: 187ms	remaining: 7.28s
25:	learn: 0.6549950	total: 195ms	remaining: 7.3s
26:	learn: 0.6538887	total: 202ms	remaining: 7.29s
27:	learn: 0.6528483	total: 209ms	remaining: 7.24s
28:	learn: 0.6515129	total: 215ms	remaining: 7.19s
29:	learn: 0.6508306	total: 227ms	remaining: 7.33s
30:	learn: 0.6502124	total: 233ms	remaining: 7.29s
31:	learn: 0.6492017	total: 241ms	remaining: 7.29s
32:	learn: 0.6482353	total: 247ms	remaining: 7.23s
33:	learn: 0.6470114	total: 255ms	remaining: 7.25s
34:	learn: 0.6452718	total: 261ms	remaining: 7.21s
35:	learn: 0.6443632	total: 269ms	remaining: 7.21s
36:	learn: 0.6435562	total: 275ms	remaining: 7.17s
37:	learn: 0.6428809	total: 283ms	remaining: 7.15s
38:	learn: 0.6422778	total: 289ms	remaining: 7.11s
39:	learn: 0.6410901	total: 295ms	remaining: 7.08s
40:	learn: 0.6405456	total: 305ms	remaining: 7.13s
41:	learn: 0.6396017	total: 311ms	remaining: 7.09s
42:	learn: 0.6385574	total: 321ms	remaining: 7.15s
43:	learn: 0.6375041	total: 330ms	remaining: 7.16s
44:	learn: 0.6366086	total: 336ms	remaining: 7.13s
45:	learn: 0.6356476	total: 342ms	remaining: 7.09s
46:	learn: 0.6350531	total: 351ms	remaining: 7.12s
47:	learn: 0.6336584	total: 363ms	remaining: 7.2s
48:	learn: 0.6327447	total: 371ms	remaining: 7.2s
49:	learn: 0.6318986	total: 378ms	remaining: 7.17s
50:	learn: 0.6310807	total: 384ms	remaining: 7.14s
51:	learn: 0.6302049	total: 390ms	remaining: 7.1s
52:	learn: 0.6296144	total: 399ms	remaining: 7.13s
53:	learn: 0.6283815	total: 405ms	remaining: 7.1s
54:	learn: 0.6273733	total: 415ms	remaining: 7.13s
55:	learn: 0.6265034	total: 424ms	remaining: 7.15s
56:	learn: 0.6255676	total: 431ms	remaining: 7.14s
57:	learn: 0.6248510	total: 438ms	remaining: 7.11s
58:	learn: 0.6240221	total: 447ms	remaining: 7.13s
59:	learn: 0.6233043	total: 453ms	remaining: 7.09s
60:	learn: 0.6220112	total: 461ms	remaining: 7.1s
61:	learn: 0.6212103	total: 468ms	remaining: 7.08s
62:	learn: 0.6203895	total: 476ms	remaining: 7.09s
63:	learn: 0.6197987	total: 483ms	remaining: 7.06s
64:	learn: 0.6191729	total: 494ms	remaining: 7.11s
65:	learn: 0.6186655	total: 501ms	remaining: 7.08s
66:	learn: 0.6180905	total: 509ms	remaining: 7.09s
67:	learn: 0.6175786	total: 514ms	remaining: 7.05s
68:	learn: 0.6166149	total: 526ms	remaining: 7.09s
69:	learn: 0.6160365	total: 534ms	remaining: 7.09s
70:	learn: 0.6153901	total: 545ms	remaining: 7.13s
71:	learn: 0.6146482	total: 556ms	remaining: 7.17s
72:	learn: 0.6142086	total: 562ms	remaining: 7.13s
73:	learn: 0.6134807	total: 574ms	remaining: 7.18s
74:	learn: 0.6129688	total: 582ms	remaining: 7.17s
75:	learn: 0.6120122	total: 593ms	remaining: 7.21s
76:	learn: 0.6117332	total: 599ms	remaining: 7.18s
77:	learn: 0.6113031	total: 606ms	remaining: 7.16s
78:	learn: 0.6107364	total: 613ms	remaining: 7.14s
79:	learn: 0.6102088	total: 621ms	remaining: 7.14s
80:	learn: 0.6095074	total: 633ms	remaining: 7.18s
81:	learn: 0.6085539	total: 643ms	remaining: 7.2s
82:	learn: 0.6077677	total: 652ms	remaining: 7.2s
83:	learn: 0.6071682	total: 658ms	remaining: 7.17s
84:	learn: 0.6065541	total: 668ms	remaining: 7.19s
85:	learn: 0.6060934	total: 683ms	remaining: 7.25s
86:	learn: 0.6057473	total: 688ms	remaining: 7.22s
87:	learn: 0.6048529	total: 700ms	remaining: 7.26s
88:	learn: 0.6044532	total: 707ms	remaining: 7.24s
89:	learn: 0.6040118	total: 714ms	remaining: 7.22s
90:	learn: 0.6031578	total: 720ms	remaining: 7.19s
91:	learn: 0.6028406	total: 726ms	remaining: 7.16s
92:	learn: 0.6024022	total: 733ms	remaining: 7.15s
93:	learn: 0.6018660	total: 739ms	remaining: 7.12s
94:	learn: 0.6012643	total: 747ms	remaining: 7.12s
95:	learn: 0.6007854	total: 753ms	remaining: 7.09s
96:	learn: 0.6000345	total: 762ms	remaining: 7.09s
97:	learn: 0.5993815	total: 768ms	remaining: 7.07s
98:	learn: 0.5988455	total: 783ms	remaining: 7.12s
99:	learn: 0.5981031	total: 788ms	remaining: 7.09s
100:	learn: 0.5972160	total: 799ms	remaining: 7.11s
101:	learn: 0.5967750	total: 804ms	remaining: 7.08s
102:	learn: 0.5961657	total: 814ms	remaining: 7.08s
103:	learn: 0.5957273	total: 820ms	remaining: 7.06s
104:	learn: 0.5952270	total: 832ms	remaining: 7.09s
105:	learn: 0.5948708	total: 839ms	remaining: 7.08s
106:	learn: 0.5945012	total: 845ms	remaining: 7.05s
107:	learn: 0.5938822	total: 852ms	remaining: 7.04s
108:	learn: 0.5935136	total: 860ms	remaining: 7.03s
109:	learn: 0.5930413	total: 868ms	remaining: 7.03s
110:	learn: 0.5927528	total: 879ms	remaining: 7.04s
111:	learn: 0.5922075	total: 885ms	remaining: 7.01s
112:	learn: 0.5916013	total: 892ms	remaining: 7s
113:	learn: 0.5913404	total: 898ms	remaining: 6.98s
114:	learn: 0.5909973	total: 905ms	remaining: 6.96s
115:	learn: 0.5904926	total: 911ms	remaining: 6.94s
116:	learn: 0.5900829	total: 920ms	remaining: 6.94s
117:	learn: 0.5896392	total: 926ms	remaining: 6.92s
118:	learn: 0.5889631	total: 932ms	remaining: 6.9s
119:	learn: 0.5884155	total: 941ms	remaining: 6.9s
120:	learn: 0.5880815	total: 946ms	remaining: 6.87s
121:	learn: 0.5875772	total: 955ms	remaining: 6.88s
122:	learn: 0.5868726	total: 963ms	remaining: 6.87s
123:	learn: 0.5864655	total: 974ms	remaining: 6.88s
124:	learn: 0.5860170	total: 990ms	remaining: 6.93s
125:	learn: 0.5852024	total: 997ms	remaining: 6.92s
126:	learn: 0.5847214	total: 1s	remaining: 6.91s
127:	learn: 0.5844665	total: 1.01s	remaining: 6.91s
128:	learn: 0.5838203	total: 1.02s	remaining: 6.89s
129:	learn: 0.5833018	total: 1.03s	remaining: 6.89s
130:	learn: 0.5830866	total: 1.04s	remaining: 6.88s
131:	learn: 0.5826765	total: 1.05s	remaining: 6.9s
132:	learn: 0.5821338	total: 1.07s	remaining: 6.96s
133:	learn: 0.5817633	total: 1.08s	remaining: 6.98s
134:	learn: 0.5814118	total: 1.1s	remaining: 7.06s
135:	learn: 0.5809864	total: 1.11s	remaining: 7.07s
136:	learn: 0.5805719	total: 1.14s	remaining: 7.16s
137:	learn: 0.5800142	total: 1.14s	remaining: 7.15s
138:	learn: 0.5797634	total: 1.15s	remaining: 7.13s
139:	learn: 0.5794083	total: 1.16s	remaining: 7.14s
140:	learn: 0.5787531	total: 1.17s	remaining: 7.13s
141:	learn: 0.5781369	total: 1.18s	remaining: 7.12s
142:	learn: 0.5776965	total: 1.18s	remaining: 7.1s
143:	learn: 0.5770423	total: 1.2s	remaining: 7.11s
144:	learn: 0.5766197	total: 1.21s	remaining: 7.12s
145:	learn: 0.5759633	total: 1.22s	remaining: 7.14s
146:	learn: 0.5756714	total: 1.23s	remaining: 7.16s
147:	learn: 0.5752389	total: 1.24s	remaining: 7.15s
148:	learn: 0.5746233	total: 1.25s	remaining: 7.13s
149:	learn: 0.5739410	total: 1.26s	remaining: 7.12s
150:	learn: 0.5733399	total: 1.26s	remaining: 7.1s
151:	learn: 0.5730177	total: 1.28s	remaining: 7.12s
152:	learn: 0.5724686	total: 1.28s	remaining: 7.1s
153:	learn: 0.5717099	total: 1.29s	remaining: 7.08s
154:	learn: 0.5713676	total: 1.29s	remaining: 7.06s
155:	learn: 0.5711139	total: 1.3s	remaining: 7.05s
156:	learn: 0.5709157	total: 1.31s	remaining: 7.03s
157:	learn: 0.5705230	total: 1.31s	remaining: 7.01s
158:	learn: 0.5701413	total: 1.32s	remaining: 6.99s
159:	learn: 0.5697342	total: 1.33s	remaining: 6.98s
160:	learn: 0.5692468	total: 1.34s	remaining: 6.97s
161:	learn: 0.5688652	total: 1.35s	remaining: 6.96s
162:	learn: 0.5685233	total: 1.35s	remaining: 6.96s
163:	learn: 0.5680360	total: 1.36s	remaining: 6.94s
164:	learn: 0.5677897	total: 1.37s	remaining: 6.94s
165:	learn: 0.5671107	total: 1.38s	remaining: 6.92s
166:	learn: 0.5664548	total: 1.39s	remaining: 6.91s
167:	learn: 0.5660677	total: 1.4s	remaining: 6.94s
168:	learn: 0.5656314	total: 1.41s	remaining: 6.95s
169:	learn: 0.5653482	total: 1.43s	remaining: 6.97s
170:	learn: 0.5649183	total: 1.44s	remaining: 6.98s
171:	learn: 0.5644282	total: 1.45s	remaining: 6.97s
172:	learn: 0.5638782	total: 1.45s	remaining: 6.95s
173:	learn: 0.5632752	total: 1.46s	remaining: 6.94s
174:	learn: 0.5627693	total: 1.47s	remaining: 6.92s
175:	learn: 0.5625323	total: 1.48s	remaining: 6.91s
176:	learn: 0.5620400	total: 1.48s	remaining: 6.9s
177:	learn: 0.5618111	total: 1.49s	remaining: 6.89s
178:	learn: 0.5616212	total: 1.5s	remaining: 6.87s
179:	learn: 0.5613292	total: 1.51s	remaining: 6.86s
180:	learn: 0.5609818	total: 1.51s	remaining: 6.85s
181:	learn: 0.5605707	total: 1.52s	remaining: 6.83s
182:	learn: 0.5601907	total: 1.53s	remaining: 6.82s
183:	learn: 0.5595807	total: 1.53s	remaining: 6.8s
184:	learn: 0.5592646	total: 1.54s	remaining: 6.79s
185:	learn: 0.5587991	total: 1.55s	remaining: 6.77s
186:	learn: 0.5586156	total: 1.55s	remaining: 6.75s
187:	learn: 0.5583108	total: 1.56s	remaining: 6.74s
188:	learn: 0.5581402	total: 1.57s	remaining: 6.72s
189:	learn: 0.5576383	total: 1.58s	remaining: 6.72s
190:	learn: 0.5573452	total: 1.58s	remaining: 6.7s
191:	learn: 0.5569204	total: 1.59s	remaining: 6.69s
192:	learn: 0.5566064	total: 1.59s	remaining: 6.67s
193:	learn: 0.5563322	total: 1.6s	remaining: 6.66s
194:	learn: 0.5559762	total: 1.61s	remaining: 6.65s
195:	learn: 0.5555091	total: 1.62s	remaining: 6.65s
196:	learn: 0.5551732	total: 1.64s	remaining: 6.67s
197:	learn: 0.5547241	total: 1.64s	remaining: 6.65s
198:	learn: 0.5544391	total: 1.65s	remaining: 6.64s
199:	learn: 0.5540434	total: 1.66s	remaining: 6.63s
200:	learn: 0.5536097	total: 1.67s	remaining: 6.62s
201:	learn: 0.5531872	total: 1.67s	remaining: 6.61s
202:	learn: 0.5528747	total: 1.68s	remaining: 6.6s
203:	learn: 0.5523987	total: 1.69s	remaining: 6.58s
204:	learn: 0.5521917	total: 1.69s	remaining: 6.57s
205:	learn: 0.5517579	total: 1.7s	remaining: 6.56s
206:	learn: 0.5513527	total: 1.71s	remaining: 6.54s
207:	learn: 0.5510601	total: 1.72s	remaining: 6.54s
208:	learn: 0.5508199	total: 1.73s	remaining: 6.53s
209:	learn: 0.5506608	total: 1.73s	remaining: 6.52s
210:	learn: 0.5502930	total: 1.74s	remaining: 6.5s
211:	learn: 0.5500272	total: 1.75s	remaining: 6.5s
212:	learn: 0.5496242	total: 1.75s	remaining: 6.48s
213:	learn: 0.5493639	total: 1.76s	remaining: 6.47s
214:	learn: 0.5491366	total: 1.77s	remaining: 6.45s
215:	learn: 0.5489250	total: 1.77s	remaining: 6.43s
216:	learn: 0.5487579	total: 1.78s	remaining: 6.42s
217:	learn: 0.5484155	total: 1.78s	remaining: 6.41s
218:	learn: 0.5480611	total: 1.79s	remaining: 6.4s
219:	learn: 0.5477724	total: 1.8s	remaining: 6.38s
220:	learn: 0.5475640	total: 1.8s	remaining: 6.37s
221:	learn: 0.5471309	total: 1.81s	remaining: 6.35s
222:	learn: 0.5467914	total: 1.82s	remaining: 6.33s
223:	learn: 0.5465221	total: 1.83s	remaining: 6.33s
224:	learn: 0.5461851	total: 1.83s	remaining: 6.31s
225:	learn: 0.5458035	total: 1.84s	remaining: 6.31s
226:	learn: 0.5454573	total: 1.85s	remaining: 6.29s
227:	learn: 0.5450628	total: 1.86s	remaining: 6.29s
228:	learn: 0.5447236	total: 1.86s	remaining: 6.28s
229:	learn: 0.5442705	total: 1.88s	remaining: 6.28s
230:	learn: 0.5440144	total: 1.88s	remaining: 6.26s
231:	learn: 0.5438082	total: 1.89s	remaining: 6.25s
232:	learn: 0.5434149	total: 1.9s	remaining: 6.24s
233:	learn: 0.5430986	total: 1.9s	remaining: 6.23s
234:	learn: 0.5427476	total: 1.91s	remaining: 6.21s
235:	learn: 0.5422636	total: 1.91s	remaining: 6.2s
236:	learn: 0.5419787	total: 1.92s	remaining: 6.19s
237:	learn: 0.5414096	total: 1.93s	remaining: 6.18s
238:	learn: 0.5412536	total: 1.94s	remaining: 6.17s
239:	learn: 0.5409476	total: 1.95s	remaining: 6.16s
240:	learn: 0.5405100	total: 1.95s	remaining: 6.15s
241:	learn: 0.5402452	total: 1.96s	remaining: 6.14s
242:	learn: 0.5399835	total: 1.97s	remaining: 6.13s
243:	learn: 0.5397552	total: 1.97s	remaining: 6.12s
244:	learn: 0.5393638	total: 1.98s	remaining: 6.11s
245:	learn: 0.5389843	total: 1.99s	remaining: 6.1s
246:	learn: 0.5386543	total: 2s	remaining: 6.1s
247:	learn: 0.5383469	total: 2.01s	remaining: 6.09s
248:	learn: 0.5381784	total: 2.02s	remaining: 6.08s
249:	learn: 0.5378034	total: 2.02s	remaining: 6.07s
250:	learn: 0.5373189	total: 2.03s	remaining: 6.07s
251:	learn: 0.5369561	total: 2.04s	remaining: 6.06s
252:	learn: 0.5365539	total: 2.05s	remaining: 6.05s
253:	learn: 0.5361710	total: 2.06s	remaining: 6.04s
254:	learn: 0.5359144	total: 2.06s	remaining: 6.03s
255:	learn: 0.5356447	total: 2.07s	remaining: 6.02s
256:	learn: 0.5354121	total: 2.08s	remaining: 6.01s
257:	learn: 0.5350640	total: 2.08s	remaining: 5.99s
258:	learn: 0.5347021	total: 2.09s	remaining: 5.98s
259:	learn: 0.5343244	total: 2.1s	remaining: 5.97s
260:	learn: 0.5339863	total: 2.1s	remaining: 5.96s
261:	learn: 0.5336496	total: 2.12s	remaining: 5.96s
262:	learn: 0.5333773	total: 2.12s	remaining: 5.95s
263:	learn: 0.5330519	total: 2.13s	remaining: 5.94s
264:	learn: 0.5327102	total: 2.14s	remaining: 5.93s
265:	learn: 0.5323938	total: 2.15s	remaining: 5.92s
266:	learn: 0.5321891	total: 2.15s	remaining: 5.91s
267:	learn: 0.5319509	total: 2.16s	remaining: 5.9s
268:	learn: 0.5317212	total: 2.17s	remaining: 5.88s
269:	learn: 0.5314861	total: 2.17s	remaining: 5.87s
270:	learn: 0.5311101	total: 2.18s	remaining: 5.86s
271:	learn: 0.5307885	total: 2.19s	remaining: 5.85s
272:	learn: 0.5303264	total: 2.19s	remaining: 5.84s
273:	learn: 0.5299853	total: 2.2s	remaining: 5.83s
274:	learn: 0.5296168	total: 2.21s	remaining: 5.82s
275:	learn: 0.5293555	total: 2.21s	remaining: 5.8s
276:	learn: 0.5290267	total: 2.22s	remaining: 5.79s
277:	learn: 0.5288823	total: 2.23s	remaining: 5.79s
278:	learn: 0.5286611	total: 2.23s	remaining: 5.78s
279:	learn: 0.5282074	total: 2.24s	remaining: 5.77s
280:	learn: 0.5279171	total: 2.25s	remaining: 5.75s
281:	learn: 0.5275769	total: 2.26s	remaining: 5.74s
282:	learn: 0.5274026	total: 2.26s	remaining: 5.73s
283:	learn: 0.5270656	total: 2.27s	remaining: 5.73s
284:	learn: 0.5267247	total: 2.29s	remaining: 5.73s
285:	learn: 0.5265373	total: 2.29s	remaining: 5.73s
286:	learn: 0.5262118	total: 2.31s	remaining: 5.74s
287:	learn: 0.5258565	total: 2.32s	remaining: 5.74s
288:	learn: 0.5255781	total: 2.34s	remaining: 5.75s
289:	learn: 0.5252025	total: 2.35s	remaining: 5.76s
290:	learn: 0.5247473	total: 2.37s	remaining: 5.78s
291:	learn: 0.5244780	total: 2.39s	remaining: 5.79s
292:	learn: 0.5241493	total: 2.4s	remaining: 5.79s
293:	learn: 0.5239387	total: 2.41s	remaining: 5.78s
294:	learn: 0.5236781	total: 2.42s	remaining: 5.78s
295:	learn: 0.5232608	total: 2.43s	remaining: 5.79s
296:	learn: 0.5229900	total: 2.45s	remaining: 5.8s
297:	learn: 0.5228774	total: 2.46s	remaining: 5.79s
298:	learn: 0.5224375	total: 2.47s	remaining: 5.78s
299:	learn: 0.5221158	total: 2.47s	remaining: 5.77s
300:	learn: 0.5218991	total: 2.48s	remaining: 5.76s
301:	learn: 0.5215783	total: 2.49s	remaining: 5.75s
302:	learn: 0.5213582	total: 2.5s	remaining: 5.74s
303:	learn: 0.5210814	total: 2.5s	remaining: 5.73s
304:	learn: 0.5209302	total: 2.51s	remaining: 5.72s
305:	learn: 0.5207496	total: 2.52s	remaining: 5.71s
306:	learn: 0.5205788	total: 2.52s	remaining: 5.7s
307:	learn: 0.5203692	total: 2.53s	remaining: 5.69s
308:	learn: 0.5199675	total: 2.54s	remaining: 5.68s
309:	learn: 0.5195666	total: 2.55s	remaining: 5.67s
310:	learn: 0.5193594	total: 2.55s	remaining: 5.66s
311:	learn: 0.5191225	total: 2.56s	remaining: 5.65s
312:	learn: 0.5187710	total: 2.57s	remaining: 5.63s
313:	learn: 0.5185435	total: 2.58s	remaining: 5.63s
314:	learn: 0.5182975	total: 2.58s	remaining: 5.62s
315:	learn: 0.5180591	total: 2.61s	remaining: 5.65s
316:	learn: 0.5177648	total: 2.62s	remaining: 5.64s
317:	learn: 0.5174111	total: 2.63s	remaining: 5.63s
318:	learn: 0.5170333	total: 2.64s	remaining: 5.63s
319:	learn: 0.5167173	total: 2.65s	remaining: 5.62s
320:	learn: 0.5166059	total: 2.66s	remaining: 5.62s
321:	learn: 0.5163073	total: 2.67s	remaining: 5.61s
322:	learn: 0.5158463	total: 2.68s	remaining: 5.61s
323:	learn: 0.5155479	total: 2.69s	remaining: 5.61s
324:	learn: 0.5152583	total: 2.7s	remaining: 5.6s
325:	learn: 0.5149200	total: 2.71s	remaining: 5.61s
326:	learn: 0.5146987	total: 2.72s	remaining: 5.6s
327:	learn: 0.5143535	total: 2.73s	remaining: 5.59s
328:	learn: 0.5141091	total: 2.74s	remaining: 5.6s
329:	learn: 0.5137703	total: 2.76s	remaining: 5.61s
330:	learn: 0.5133229	total: 2.77s	remaining: 5.61s
331:	learn: 0.5131334	total: 2.79s	remaining: 5.61s
332:	learn: 0.5129140	total: 2.79s	remaining: 5.59s
333:	learn: 0.5127037	total: 2.8s	remaining: 5.58s
334:	learn: 0.5123756	total: 2.81s	remaining: 5.57s
335:	learn: 0.5119502	total: 2.82s	remaining: 5.57s
336:	learn: 0.5117856	total: 2.82s	remaining: 5.56s
337:	learn: 0.5116567	total: 2.84s	remaining: 5.55s
338:	learn: 0.5114263	total: 2.84s	remaining: 5.54s
339:	learn: 0.5111304	total: 2.86s	remaining: 5.55s
340:	learn: 0.5109152	total: 2.87s	remaining: 5.54s
341:	learn: 0.5107474	total: 2.88s	remaining: 5.54s
342:	learn: 0.5104794	total: 2.89s	remaining: 5.53s
343:	learn: 0.5101194	total: 2.9s	remaining: 5.53s
344:	learn: 0.5098395	total: 2.91s	remaining: 5.53s
345:	learn: 0.5097043	total: 2.94s	remaining: 5.56s
346:	learn: 0.5093589	total: 2.96s	remaining: 5.57s
347:	learn: 0.5090270	total: 2.98s	remaining: 5.58s
348:	learn: 0.5087102	total: 3s	remaining: 5.6s
349:	learn: 0.5084711	total: 3.02s	remaining: 5.61s
350:	learn: 0.5082411	total: 3.03s	remaining: 5.6s
351:	learn: 0.5080227	total: 3.04s	remaining: 5.59s
352:	learn: 0.5078818	total: 3.04s	remaining: 5.58s
353:	learn: 0.5076237	total: 3.05s	remaining: 5.57s
354:	learn: 0.5073005	total: 3.06s	remaining: 5.55s
355:	learn: 0.5070524	total: 3.07s	remaining: 5.55s
356:	learn: 0.5066066	total: 3.09s	remaining: 5.56s
357:	learn: 0.5063124	total: 3.09s	remaining: 5.55s
358:	learn: 0.5059759	total: 3.1s	remaining: 5.54s
359:	learn: 0.5055636	total: 3.11s	remaining: 5.53s
360:	learn: 0.5053709	total: 3.12s	remaining: 5.53s
361:	learn: 0.5050434	total: 3.13s	remaining: 5.52s
362:	learn: 0.5048092	total: 3.15s	remaining: 5.53s
363:	learn: 0.5045937	total: 3.17s	remaining: 5.53s
364:	learn: 0.5043361	total: 3.17s	remaining: 5.52s
365:	learn: 0.5041881	total: 3.18s	remaining: 5.5s
366:	learn: 0.5039147	total: 3.18s	remaining: 5.49s
367:	learn: 0.5036582	total: 3.19s	remaining: 5.48s
368:	learn: 0.5034450	total: 3.2s	remaining: 5.47s
369:	learn: 0.5031893	total: 3.21s	remaining: 5.46s
370:	learn: 0.5030478	total: 3.22s	remaining: 5.46s
371:	learn: 0.5027549	total: 3.23s	remaining: 5.46s
372:	learn: 0.5024928	total: 3.24s	remaining: 5.45s
373:	learn: 0.5022764	total: 3.25s	remaining: 5.45s

,Model,Accuracy,Precision,Recall,F1,ROC-AUC,PR-AUC,Balanced Accuracy
0,Logistic Regression,0.610,0.000,0.000,0.000,0.548,0.490,0.500
1,LDA,0.610,0.000,0.000,0.000,0.548,0.490,0.500
2,QDA,0.657,0.632,0.289,0.397,0.668,0.602,0.591
3,Decision Tree,0.584,0.463,0.418,0.439,0.554,0.421,0.554
4,Random Forest,0.662,0.637,0.309,0.416,0.654,0.587,0.598
5,Gradient Boosting,0.652,0.643,0.246,0.356,0.626,0.550,0.579
6,XGBoost,0.622,0.526,0.320,0.398,0.624,0.554,0.568
7,LightGBM,0.659,0.603,0.367,0.456,0.645,0.580,0.606
8,CatBoost,0.662,0.620,0.344,0.442,0.676,0.604,0.604
9,KNN,0.614,0.509,0.320,0.393,0.598,0.470,0.561
10,Naive Bayes,0.614,0.516,0.188,0.275,0.609,0.487,0.537

In [29]:
models = {
    "Logistic Regression": LogisticRegression(),
    "LDA": LinearDiscriminantAnalysis(),
    "QDA": QuadraticDiscriminantAnalysis(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "XGBoost": XGBClassifier(),
    "LightGBM": LGBMClassifier(),
    "CatBoost": CatBoostClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}



for name, model in models.items():

    model.fit(X_train, y_train)

    y_predict = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_predict)
    precision = precision_score(y_test, y_predict)
    recall = recall_score(y_test, y_predict)
    f1 = f1_score(y_test, y_predict)

    print(f"\n{name}")
    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1       : {f1:.4f}")

c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\IGO\OneDrive\Bureau\WATER\WATER_POTABILITY_PROJECT\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Logistic Regression
Accuracy : 0.6098
Precision: 0.0000
Recall   : 0.0000
F1       : 0.0000

LDA
Accuracy : 0.6098
Precision: 0.0000
Recall   : 0.0000
F1       : 0.0000

QDA
Accuracy : 0.6570
Precision: 0.6325
Recall   : 0.2891
F1       : 0.3968

Decision Tree
Accuracy : 0.5945
Precision: 0.4800
Recall   : 0.4688
F1       : 0.4743

Random Forest
Accuracy : 0.6555
Precision: 0.6190
Recall   : 0.3047
F1       : 0.4084

Gradient Boosting
Accuracy : 0.6524
Precision: 0.6429
Recall   : 0.2461
F1       : 0.3559

XGBoost
Accuracy : 0.6220
Precision: 0.5256
Recall   : 0.3203
F1       : 0.3981
[LightGBM] [Info] Number of positive: 1022, number of negative: 1598
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000261 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2295
[LightGBM] [Info] Number of data points in the train set: 2620, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.390076 -> initscore=-0.446991
[LightGBM] [Info] Start training from score -0.446991

LightGBM
Accuracy : 0.6585
Precision: 0.6026
Recall   : 0.3672
F1       : 0.4563
Learning rate set to 0.015543
0:	learn: 0.6907566	total: 5.65ms	remaining: 5.65s
1:	learn: 0.6895101	total: 10.8ms	remaining: 5.4s
2:	learn: 0.6878912	total: 18.8ms	remaining: 6.25s
3:	learn: 0.6860822	total: 24.1ms	remaining: 6.01s
4:	learn: 0.6841549	total: 32.8ms	remaining: 6.54s
5:	learn: 0.6827359	total: 38.8ms	remaining: 6.42s
6:	learn: 0.6811870	total: 47ms	remaining: 6.67s
7:	learn: 0.6799684	total: 54.2ms	remaining: 6.72s
8:	learn: 0.6784943	total: 59.4ms	remaining: 6.54s
9:	learn: 0.6768095	total: 66.9ms	remaining: 6.63s
10:	learn: 0.6754283	total: 74.3ms	remaining: 6.68s
11:	learn: 0.6735641	total: 81.9ms	remaining: 6.75s
12:	learn: 0.6721659	total: 87.5ms	remaining: 6.64s
13:	learn: 0.6712741	total: 94.7ms	remaining: 6.67s
14:	learn: 0.6700972	total: 100ms	remaining: 6.58s
15:	learn: 0.6691290	total: 106ms	remaining: 6.5s
16:	learn: 0.6669841	total: 113ms	remaining: 6.55s
17:	learn: 0.6652379	total: 119ms	remaining: 6.49s
18:	learn: 0.6638841	total: 125ms	remaining: 6.47s
19:	learn: 0.6623570	total: 132ms	remaining: 6.48s
20:	learn: 0.6609614	total: 138ms	remaining: 6.43s
21:	learn: 0.6599522	total: 146ms	remaining: 6.47s
22:	learn: 0.6590445	total: 151ms	remaining: 6.42s
23:	learn: 0.6576270	total: 158ms	remaining: 6.42s
24:	learn: 0.6562864	total: 164ms	remaining: 6.39s
25:	learn: 0.6549950	total: 170ms	remaining: 6.35s
26:	learn: 0.6538887	total: 177ms	remaining: 6.38s
27:	learn: 0.6528483	total: 183ms	remaining: 6.34s
28:	learn: 0.6515129	total: 190ms	remaining: 6.35s
29:	learn: 0.6508306	total: 195ms	remaining: 6.32s
30:	learn: 0.6502124	total: 201ms	remaining: 6.29s
31:	learn: 0.6492017	total: 212ms	remaining: 6.4s
32:	learn: 0.6482353	total: 217ms	remaining: 6.36s
33:	learn: 0.6470114	total: 225ms	remaining: 6.38s
34:	learn: 0.6452718	total: 231ms	remaining: 6.36s
35:	learn: 0.6443632	total: 241ms	remaining: 6.45s
36:	learn: 0.6435562	total: 246ms	remaining: 6.42s
37:	learn: 0.6428809	total: 255ms	remaining: 6.46s
38:	learn: 0.6422778	total: 261ms	remaining: 6.43s
39:	learn: 0.6410901	total: 267ms	remaining: 6.42s
40:	learn: 0.6405456	total: 274ms	remaining: 6.4s
41:	learn: 0.6396017	total: 279ms	remaining: 6.37s
42:	learn: 0.6385574	total: 287ms	remaining: 6.38s
43:	learn: 0.6375041	total: 292ms	remaining: 6.35s
44:	learn: 0.6366086	total: 298ms	remaining: 6.32s
45:	learn: 0.6356476	total: 305ms	remaining: 6.32s
46:	learn: 0.6350531	total: 310ms	remaining: 6.29s
47:	learn: 0.6336584	total: 318ms	remaining: 6.3s
48:	learn: 0.6327447	total: 325ms	remaining: 6.32s
49:	learn: 0.6318986	total: 333ms	remaining: 6.32s
50:	learn: 0.6310807	total: 338ms	remaining: 6.29s
51:	learn: 0.6302049	total: 346ms	remaining: 6.3s
52:	learn: 0.6296144	total: 352ms	remaining: 6.29s
53:	learn: 0.6283815	total: 358ms	remaining: 6.26s
54:	learn: 0.6273733	total: 365ms	remaining: 6.26s
55:	learn: 0.6265034	total: 371ms	remaining: 6.25s
56:	learn: 0.6255676	total: 376ms	remaining: 6.22s
57:	learn: 0.6248510	total: 385ms	remaining: 6.25s
58:	learn: 0.6240221	total: 390ms	remaining: 6.22s
59:	learn: 0.6233043	total: 397ms	remaining: 6.23s
60:	learn: 0.6220112	total: 403ms	remaining: 6.2s
61:	learn: 0.6212103	total: 409ms	remaining: 6.18s
62:	learn: 0.6203895	total: 416ms	remaining: 6.19s
63:	learn: 0.6197987	total: 422ms	remaining: 6.17s
64:	learn: 0.6191729	total: 430ms	remaining: 6.18s
65:	learn: 0.6186655	total: 435ms	remaining: 6.16s
66:	learn: 0.6180905	total: 442ms	remaining: 6.15s
67:	learn: 0.6175786	total: 448ms	remaining: 6.14s
68:	learn: 0.6166149	total: 455ms	remaining: 6.14s
69:	learn: 0.6160365	total: 465ms	remaining: 6.17s
70:	learn: 0.6153901	total: 472ms	remaining: 6.17s
71:	learn: 0.6146482	total: 479ms	remaining: 6.17s
72:	learn: 0.6142086	total: 484ms	remaining: 6.15s
73:	learn: 0.6134807	total: 491ms	remaining: 6.15s
74:	learn: 0.6129688	total: 497ms	remaining: 6.13s
75:	learn: 0.6120122	total: 502ms	remaining: 6.11s
76:	learn: 0.6117332	total: 510ms	remaining: 6.11s
77:	learn: 0.6113031	total: 516ms	remaining: 6.09s
78:	learn: 0.6107364	total: 523ms	remaining: 6.1s
79:	learn: 0.6102088	total: 530ms	remaining: 6.1s
80:	learn: 0.6095074	total: 536ms	remaining: 6.08s
81:	learn: 0.6085539	total: 542ms	remaining: 6.07s
82:	learn: 0.6077677	total: 548ms	remaining: 6.05s
83:	learn: 0.6071682	total: 555ms	remaining: 6.06s
84:	learn: 0.6065541	total: 561ms	remaining: 6.04s
85:	learn: 0.6060934	total: 567ms	remaining: 6.03s
86:	learn: 0.6057473	total: 575ms	remaining: 6.03s
87:	learn: 0.6048529	total: 581ms	remaining: 6.02s
88:	learn: 0.6044532	total: 588ms	remaining: 6.02s
89:	learn: 0.6040118	total: 593ms	remaining: 6s
90:	learn: 0.6031578	total: 601ms	remaining: 6s
91:	learn: 0.6028406	total: 607ms	remaining: 5.99s
92:	learn: 0.6024022	total: 612ms	remaining: 5.97s
93:	learn: 0.6018660	total: 622ms	remaining: 5.99s
94:	learn: 0.6012643	total: 628ms	remaining: 5.98s
95:	learn: 0.6007854	total: 637ms	remaining: 6s
96:	learn: 0.6000345	total: 649ms	remaining: 6.04s
97:	learn: 0.5993815	total: 658ms	remaining: 6.06s
98:	learn: 0.5988455	total: 671ms	remaining: 6.11s
99:	learn: 0.5981031	total: 685ms	remaining: 6.17s
100:	learn: 0.5972160	total: 691ms	remaining: 6.15s
101:	learn: 0.5967750	total: 699ms	remaining: 6.15s
102:	learn: 0.5961657	total: 705ms	remaining: 6.14s
103:	learn: 0.5957273	total: 712ms	remaining: 6.14s
104:	learn: 0.5952270	total: 718ms	remaining: 6.12s
105:	learn: 0.5948708	total: 724ms	remaining: 6.1s
106:	learn: 0.5945012	total: 731ms	remaining: 6.1s
107:	learn: 0.5938822	total: 737ms	remaining: 6.09s
108:	learn: 0.5935136	total: 744ms	remaining: 6.08s
109:	learn: 0.5930413	total: 750ms	remaining: 6.07s
110:	learn: 0.5927528	total: 756ms	remaining: 6.05s
111:	learn: 0.5922075	total: 765ms	remaining: 6.07s
112:	learn: 0.5916013	total: 771ms	remaining: 6.05s
113:	learn: 0.5913404	total: 780ms	remaining: 6.06s
114:	learn: 0.5909973	total: 785ms	remaining: 6.04s
115:	learn: 0.5904926	total: 792ms	remaining: 6.03s
116:	learn: 0.5900829	total: 797ms	remaining: 6.02s
117:	learn: 0.5896392	total: 803ms	remaining: 6s
118:	learn: 0.5889631	total: 813ms	remaining: 6.02s
119:	learn: 0.5884155	total: 819ms	remaining: 6s
120:	learn: 0.5880815	total: 827ms	remaining: 6.01s
121:	learn: 0.5875772	total: 833ms	remaining: 5.99s
122:	learn: 0.5868726	total: 841ms	remaining: 6s
123:	learn: 0.5864655	total: 848ms	remaining: 5.99s
124:	learn: 0.5860170	total: 855ms	remaining: 5.98s
125:	learn: 0.5852024	total: 861ms	remaining: 5.97s
126:	learn: 0.5847214	total: 867ms	remaining: 5.96s
127:	learn: 0.5844665	total: 874ms	remaining: 5.95s
128:	learn: 0.5838203	total: 879ms	remaining: 5.93s
129:	learn: 0.5833018	total: 885ms	remaining: 5.92s
130:	learn: 0.5830866	total: 891ms	remaining: 5.91s
131:	learn: 0.5826765	total: 897ms	remaining: 5.9s
132:	learn: 0.5821338	total: 905ms	remaining: 5.9s
133:	learn: 0.5817633	total: 910ms	remaining: 5.88s
134:	learn: 0.5814118	total: 916ms	remaining: 5.87s
135:	learn: 0.5809864	total: 923ms	remaining: 5.86s
136:	learn: 0.5805719	total: 928ms	remaining: 5.85s
137:	learn: 0.5800142	total: 935ms	remaining: 5.84s
138:	learn: 0.5797634	total: 941ms	remaining: 5.83s
139:	learn: 0.5794083	total: 946ms	remaining: 5.81s
140:	learn: 0.5787531	total: 955ms	remaining: 5.82s
141:	learn: 0.5781369	total: 966ms	remaining: 5.83s
142:	learn: 0.5776965	total: 972ms	remaining: 5.83s
143:	learn: 0.5770423	total: 978ms	remaining: 5.81s
144:	learn: 0.5766197	total: 985ms	remaining: 5.81s
145:	learn: 0.5759633	total: 991ms	remaining: 5.79s
146:	learn: 0.5756714	total: 998ms	remaining: 5.79s
147:	learn: 0.5752389	total: 1s	remaining: 5.78s
148:	learn: 0.5746233	total: 1.01s	remaining: 5.77s
149:	learn: 0.5739410	total: 1.02s	remaining: 5.76s
150:	learn: 0.5733399	total: 1.02s	remaining: 5.75s
151:	learn: 0.5730177	total: 1.03s	remaining: 5.74s
152:	learn: 0.5724686	total: 1.03s	remaining: 5.73s
153:	learn: 0.5717099	total: 1.04s	remaining: 5.73s
154:	learn: 0.5713676	total: 1.05s	remaining: 5.72s
155:	learn: 0.5711139	total: 1.05s	remaining: 5.71s
156:	learn: 0.5709157	total: 1.06s	remaining: 5.71s
157:	learn: 0.5705230	total: 1.07s	remaining: 5.7s
158:	learn: 0.5701413	total: 1.07s	remaining: 5.69s
159:	learn: 0.5697342	total: 1.08s	remaining: 5.68s
160:	learn: 0.5692468	total: 1.09s	remaining: 5.67s
161:	learn: 0.5688652	total: 1.09s	remaining: 5.66s
162:	learn: 0.5685233	total: 1.1s	remaining: 5.66s
163:	learn: 0.5680360	total: 1.11s	remaining: 5.65s
164:	learn: 0.5677897	total: 1.11s	remaining: 5.64s
165:	learn: 0.5671107	total: 1.12s	remaining: 5.62s
166:	learn: 0.5664548	total: 1.13s	remaining: 5.62s
167:	learn: 0.5660677	total: 1.13s	remaining: 5.61s
168:	learn: 0.5656314	total: 1.14s	remaining: 5.6s
169:	learn: 0.5653482	total: 1.15s	remaining: 5.59s
170:	learn: 0.5649183	total: 1.15s	remaining: 5.58s
171:	learn: 0.5644282	total: 1.16s	remaining: 5.58s
172:	learn: 0.5638782	total: 1.17s	remaining: 5.57s
173:	learn: 0.5632752	total: 1.17s	remaining: 5.56s
174:	learn: 0.5627693	total: 1.18s	remaining: 5.55s
175:	learn: 0.5625323	total: 1.18s	remaining: 5.54s
176:	learn: 0.5620400	total: 1.19s	remaining: 5.54s
177:	learn: 0.5618111	total: 1.2s	remaining: 5.52s
178:	learn: 0.5616212	total: 1.2s	remaining: 5.52s
179:	learn: 0.5613292	total: 1.21s	remaining: 5.5s
180:	learn: 0.5609818	total: 1.21s	remaining: 5.49s
181:	learn: 0.5605707	total: 1.22s	remaining: 5.49s
182:	learn: 0.5601907	total: 1.23s	remaining: 5.48s
183:	learn: 0.5595807	total: 1.24s	remaining: 5.48s
184:	learn: 0.5592646	total: 1.24s	remaining: 5.48s
185:	learn: 0.5587991	total: 1.25s	remaining: 5.48s
186:	learn: 0.5586156	total: 1.26s	remaining: 5.47s
187:	learn: 0.5583108	total: 1.27s	remaining: 5.48s
188:	learn: 0.5581402	total: 1.27s	remaining: 5.47s
189:	learn: 0.5576383	total: 1.28s	remaining: 5.46s
190:	learn: 0.5573452	total: 1.29s	remaining: 5.45s
191:	learn: 0.5569204	total: 1.29s	remaining: 5.44s
192:	learn: 0.5566064	total: 1.3s	remaining: 5.44s
193:	learn: 0.5563322	total: 1.3s	remaining: 5.42s
194:	learn: 0.5559762	total: 1.31s	remaining: 5.42s
195:	learn: 0.5555091	total: 1.32s	remaining: 5.41s
196:	learn: 0.5551732	total: 1.32s	remaining: 5.4s
197:	learn: 0.5547241	total: 1.33s	remaining: 5.39s
198:	learn: 0.5544391	total: 1.34s	remaining: 5.38s
199:	learn: 0.5540434	total: 1.34s	remaining: 5.38s
200:	learn: 0.5536097	total: 1.35s	remaining: 5.37s
201:	learn: 0.5531872	total: 1.35s	remaining: 5.36s
202:	learn: 0.5528747	total: 1.36s	remaining: 5.36s
203:	learn: 0.5523987	total: 1.37s	remaining: 5.35s
204:	learn: 0.5521917	total: 1.38s	remaining: 5.35s
205:	learn: 0.5517579	total: 1.39s	remaining: 5.34s
206:	learn: 0.5513527	total: 1.39s	remaining: 5.33s
207:	learn: 0.5510601	total: 1.4s	remaining: 5.32s
208:	learn: 0.5508199	total: 1.4s	remaining: 5.31s
209:	learn: 0.5506608	total: 1.41s	remaining: 5.31s
210:	learn: 0.5502930	total: 1.42s	remaining: 5.3s
211:	learn: 0.5500272	total: 1.42s	remaining: 5.29s
212:	learn: 0.5496242	total: 1.43s	remaining: 5.28s
213:	learn: 0.5493639	total: 1.44s	remaining: 5.28s
214:	learn: 0.5491366	total: 1.44s	remaining: 5.27s
215:	learn: 0.5489250	total: 1.45s	remaining: 5.27s
216:	learn: 0.5487579	total: 1.46s	remaining: 5.27s
217:	learn: 0.5484155	total: 1.47s	remaining: 5.26s
218:	learn: 0.5480611	total: 1.47s	remaining: 5.25s
219:	learn: 0.5477724	total: 1.48s	remaining: 5.24s
220:	learn: 0.5475640	total: 1.48s	remaining: 5.23s
221:	learn: 0.5471309	total: 1.49s	remaining: 5.23s
222:	learn: 0.5467914	total: 1.5s	remaining: 5.22s
223:	learn: 0.5465221	total: 1.51s	remaining: 5.22s
224:	learn: 0.5461851	total: 1.51s	remaining: 5.21s
225:	learn: 0.5458035	total: 1.52s	remaining: 5.2s
226:	learn: 0.5454573	total: 1.52s	remaining: 5.19s
227:	learn: 0.5450628	total: 1.53s	remaining: 5.18s
228:	learn: 0.5447236	total: 1.54s	remaining: 5.17s
229:	learn: 0.5442705	total: 1.54s	remaining: 5.16s
230:	learn: 0.5440144	total: 1.55s	remaining: 5.15s
231:	learn: 0.5438082	total: 1.55s	remaining: 5.14s
232:	learn: 0.5434149	total: 1.56s	remaining: 5.13s
233:	learn: 0.5430986	total: 1.57s	remaining: 5.14s
234:	learn: 0.5427476	total: 1.58s	remaining: 5.13s
235:	learn: 0.5422636	total: 1.58s	remaining: 5.13s
236:	learn: 0.5419787	total: 1.59s	remaining: 5.12s
237:	learn: 0.5414096	total: 1.6s	remaining: 5.12s
238:	learn: 0.5412536	total: 1.6s	remaining: 5.11s
239:	learn: 0.5409476	total: 1.61s	remaining: 5.1s
240:	learn: 0.5405100	total: 1.62s	remaining: 5.1s
241:	learn: 0.5402452	total: 1.63s	remaining: 5.11s
242:	learn: 0.5399835	total: 1.64s	remaining: 5.1s
243:	learn: 0.5397552	total: 1.65s	remaining: 5.1s
244:	learn: 0.5393638	total: 1.65s	remaining: 5.09s
245:	learn: 0.5389843	total: 1.66s	remaining: 5.1s
246:	learn: 0.5386543	total: 1.67s	remaining: 5.09s
247:	learn: 0.5383469	total: 1.67s	remaining: 5.08s
248:	learn: 0.5381784	total: 1.68s	remaining: 5.08s
249:	learn: 0.5378034	total: 1.69s	remaining: 5.07s
250:	learn: 0.5373189	total: 1.7s	remaining: 5.07s
251:	learn: 0.5369561	total: 1.7s	remaining: 5.05s
252:	learn: 0.5365539	total: 1.71s	remaining: 5.05s
253:	learn: 0.5361710	total: 1.72s	remaining: 5.04s
254:	learn: 0.5359144	total: 1.72s	remaining: 5.03s
255:	learn: 0.5356447	total: 1.73s	remaining: 5.03s
256:	learn: 0.5354121	total: 1.74s	remaining: 5.02s
257:	learn: 0.5350640	total: 1.74s	remaining: 5.01s
258:	learn: 0.5347021	total: 1.75s	remaining: 5s
259:	learn: 0.5343244	total: 1.75s	remaining: 4.99s
260:	learn: 0.5339863	total: 1.76s	remaining: 5s
261:	learn: 0.5336496	total: 1.77s	remaining: 4.99s
262:	learn: 0.5333773	total: 1.78s	remaining: 4.98s
263:	learn: 0.5330519	total: 1.78s	remaining: 4.97s
264:	learn: 0.5327102	total: 1.79s	remaining: 4.96s
265:	learn: 0.5323938	total: 1.79s	remaining: 4.96s
266:	learn: 0.5321891	total: 1.8s	remaining: 4.95s
267:	learn: 0.5319509	total: 1.81s	remaining: 4.94s
268:	learn: 0.5317212	total: 1.81s	remaining: 4.93s
269:	learn: 0.5314861	total: 1.82s	remaining: 4.93s
270:	learn: 0.5311101	total: 1.83s	remaining: 4.92s
271:	learn: 0.5307885	total: 1.84s	remaining: 4.92s
272:	learn: 0.5303264	total: 1.84s	remaining: 4.91s
273:	learn: 0.5299853	total: 1.85s	remaining: 4.9s
274:	learn: 0.5296168	total: 1.86s	remaining: 4.9s
275:	learn: 0.5293555	total: 1.86s	remaining: 4.89s
276:	learn: 0.5290267	total: 1.87s	remaining: 4.89s
277:	learn: 0.5288823	total: 1.88s	remaining: 4.88s
278:	learn: 0.5286611	total: 1.89s	remaining: 4.87s
279:	learn: 0.5282074	total: 1.89s	remaining: 4.86s
280:	learn: 0.5279171	total: 1.9s	remaining: 4.86s
281:	learn: 0.5275769	total: 1.91s	remaining: 4.85s
282:	learn: 0.5274026	total: 1.91s	remaining: 4.84s
283:	learn: 0.5270656	total: 1.92s	remaining: 4.84s
284:	learn: 0.5267247	total: 1.92s	remaining: 4.83s
285:	learn: 0.5265373	total: 1.93s	remaining: 4.82s
286:	learn: 0.5262118	total: 1.94s	remaining: 4.81s
287:	learn: 0.5258565	total: 1.94s	remaining: 4.8s
288:	learn: 0.5255781	total: 1.95s	remaining: 4.79s
289:	learn: 0.5252025	total: 1.95s	remaining: 4.78s
290:	learn: 0.5247473	total: 1.96s	remaining: 4.78s
291:	learn: 0.5244780	total: 1.97s	remaining: 4.77s
292:	learn: 0.5241493	total: 1.97s	remaining: 4.76s
293:	learn: 0.5239387	total: 1.98s	remaining: 4.75s
294:	learn: 0.5236781	total: 1.98s	remaining: 4.74s
295:	learn: 0.5232608	total: 1.99s	remaining: 4.73s
296:	learn: 0.5229900	total: 2s	remaining: 4.73s
297:	learn: 0.5228774	total: 2s	remaining: 4.72s
298:	learn: 0.5224375	total: 2.01s	remaining: 4.71s
299:	learn: 0.5221158	total: 2.02s	remaining: 4.7s
300:	learn: 0.5218991	total: 2.02s	remaining: 4.69s
301:	learn: 0.5215783	total: 2.03s	remaining: 4.69s
302:	learn: 0.5213582	total: 2.04s	remaining: 4.68s
303:	learn: 0.5210814	total: 2.04s	remaining: 4.68s
304:	learn: 0.5209302	total: 2.05s	remaining: 4.67s
305:	learn: 0.5207496	total: 2.06s	remaining: 4.66s
306:	learn: 0.5205788	total: 2.06s	remaining: 4.66s
307:	learn: 0.5203692	total: 2.07s	remaining: 4.65s
308:	learn: 0.5199675	total: 2.08s	remaining: 4.65s
309:	learn: 0.5195666	total: 2.08s	remaining: 4.64s
310:	learn: 0.5193594	total: 2.09s	remaining: 4.63s
311:	learn: 0.5191225	total: 2.1s	remaining: 4.62s
312:	learn: 0.5187710	total: 2.1s	remaining: 4.61s
313:	learn: 0.5185435	total: 2.11s	remaining: 4.61s
314:	learn: 0.5182975	total: 2.12s	remaining: 4.6s
315:	learn: 0.5180591	total: 2.12s	remaining: 4.59s
316:	learn: 0.5177648	total: 2.13s	remaining: 4.58s
317:	learn: 0.5174111	total: 2.13s	remaining: 4.57s
318:	learn: 0.5170333	total: 2.14s	remaining: 4.57s
319:	learn: 0.5167173	total: 2.14s	remaining: 4.56s
320:	learn: 0.5166059	total: 2.15s	remaining: 4.55s
321:	learn: 0.5163073	total: 2.16s	remaining: 4.54s
322:	learn: 0.5158463	total: 2.17s	remaining: 4.54s
323:	learn: 0.5155479	total: 2.17s	remaining: 4.53s
324:	learn: 0.5152583	total: 2.18s	remaining: 4.52s
325:	learn: 0.5149200	total: 2.19s	remaining: 4.52s
326:	learn: 0.5146987	total: 2.19s	remaining: 4.51s
327:	learn: 0.5143535	total: 2.2s	remaining: 4.5s
328:	learn: 0.5141091	total: 2.2s	remaining: 4.5s
329:	learn: 0.5137703	total: 2.21s	remaining: 4.49s
330:	learn: 0.5133229	total: 2.21s	remaining: 4.48s
331:	learn: 0.5131334	total: 2.22s	remaining: 4.47s
332:	learn: 0.5129140	total: 2.23s	remaining: 4.46s
333:	learn: 0.5127037	total: 2.23s	remaining: 4.46s
334:	learn: 0.5123756	total: 2.24s	remaining: 4.45s
335:	learn: 0.5119502	total: 2.25s	remaining: 4.44s
336:	learn: 0.5117856	total: 2.25s	remaining: 4.44s
337:	learn: 0.5116567	total: 2.26s	remaining: 4.43s
338:	learn: 0.5114263	total: 2.27s	remaining: 4.43s
339:	learn: 0.5111304	total: 2.28s	remaining: 4.42s
340:	learn: 0.5109152	total: 2.29s	remaining: 4.42s
341:	learn: 0.5107474	total: 2.29s	remaining: 4.41s
342:	learn: 0.5104794	total: 2.3s	remaining: 4.41s
343:	learn: 0.5101194	total: 2.31s	remaining: 4.4s
344:	learn: 0.5098395	total: 2.31s	remaining: 4.39s
345:	learn: 0.5097043	total: 2.32s	remaining: 4.38s
346:	learn: 0.5093589	total: 2.32s	remaining: 4.37s
347:	learn: 0.5090270	total: 2.33s	remaining: 4.37s
348:	learn: 0.5087102	total: 2.34s	remaining: 4.36s
349:	learn: 0.5084711	total: 2.35s	remaining: 4.36s
350:	learn: 0.5082411	total: 2.35s	remaining: 4.35s
351:	learn: 0.5080227	total: 2.36s	remaining: 4.35s
352:	learn: 0.5078818	total: 2.37s	remaining: 4.34s
353:	learn: 0.5076237	total: 2.37s	remaining: 4.33s
354:	learn: 0.5073005	total: 2.38s	remaining: 4.32s
355:	learn: 0.5070524	total: 2.38s	remaining: 4.32s
356:	learn: 0.5066066	total: 2.39s	remaining: 4.31s
357:	learn: 0.5063124	total: 2.4s	remaining: 4.3s
358:	learn: 0.5059759	total: 2.4s	remaining: 4.29s
359:	learn: 0.5055636	total: 2.41s	remaining: 4.29s
360:	learn: 0.5053709	total: 2.42s	remaining: 4.28s
361:	learn: 0.5050434	total: 2.42s	remaining: 4.27s
362:	learn: 0.5048092	total: 2.43s	remaining: 4.26s
363:	learn: 0.5045937	total: 2.44s	remaining: 4.25s
364:	learn: 0.5043361	total: 2.45s	remaining: 4.26s

In [ ]:


from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV                         
    )

from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)




# ============================================================
# 2. FEATURES AND TARGET
# ============================================================

X = df.drop("Potability", axis=1)
y = df["Potability"]


# ============================================================
# 3. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ============================================================
# 4. IMPUTATION
# ============================================================

imputer = SimpleImputer(strategy="median")

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)


# ============================================================
# 5. CREATE RANDOM FOREST MODEL
# ============================================================

model = RandomForestClassifier(
    n_estimators=100,
    criterion="gini",
    class_weight="balanced",
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)


# ============================================================
# 6. TRAIN MODEL
# ============================================================

model.fit(X_train, y_train)


# ============================================================
# 7. PREDICTIONS
# ============================================================

y_pred = model.predict(X_test)


# ============================================================
# 8. EVALUATION
# ============================================================

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy  : {accuracy:.3f}")
print(f"Precision : {precision:.3f}")
print(f"Recall    : {recall:.3f}")
print(f"F1 Score  : {f1:.3f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy  : 0.643
Precision : 0.562
Recall    : 0.391
F1 Score  : 0.461

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.81      0.73       400
           1       0.56      0.39      0.46       256

    accuracy                           0.64       656
   macro avg       0.62      0.60      0.60       656
weighted avg       0.63      0.64      0.63       656


Confusion Matrix:
[[322  78]
 [156 100]]