In [1]:
import pandas as pd
from pathlib import Path
import logging as log





DATA = Path.cwd().parent.parent  /"DATASET"/"water_potability.csv"



print(DATA)

c:\Users\IGO\OneDrive\Bureau\WATER\DATASET\water_potability.csv

In [2]:
class Extraction:
    def __init__(self, source_path):
        self.source_path = source_path

    def extract_data(self) -> pd.DataFrame:
        
        try:
            # Check if the source path exists
            if not Path(self.source_path).exists():
                
                raise FileNotFoundError(f"Source path {self.source_path} does not exist.")

            # Read the data into a DataFrame
            data = pd.read_csv(self.source_path)
            
            return data

        except Exception as e:
            
            raise

In [3]:
# file checking


def file_cheking(path):


    






    return

In [4]:

f=Extraction(DATA).extract_data()
f.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [5]:

class Dataloader:
    def __init__(self,data_path:str):
        self.data_path = data_path


    def loading(self):


        DATA = Path.cwd().parent.parent  /"DATASET"/"water_potability.csv"
        return pd.read_csv(DATA)

In [6]:
kika = Dataloader(DATA).loading()
kika.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [7]:




if not DATA.is_file():
    raise FileNotFoundError(f"File not found: {DATA}")

df = pd.read_csv(DATA)

print(df.head())

         ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813

   Organic_carbon  Trihalomethanes  Turbidity  Potability
0       10.379783        86.990970   2.963135           0
1       15.180013        56.329076   4.500656           0
2       16.868637        66.420093   3.055934           0
3       18.436524       100.341674   4.628771           0
4       11.558279        31.997993   4.075075           0

In [8]:
def inspect_data(self):

        data = Extraction(self.path).extract_data()

        print("Data Inspection: start" ,data.head())

In [9]:
print("=" * 70)
print("                    DATASET INSPECTION REPORT")
print("=" * 70)

======================================================================
                    DATASET INSPECTION REPORT
======================================================================

In [10]:
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")


duplicate_percentage = (
    df.apply(lambda col: col.duplicated().mean() * 100)
      .round(2)
      .sort_values(ascending=False)
)

print(duplicate_percentage)

Number of duplicate rows: 0
Potability         99.94
Sulfate            23.81
ph                 14.96
Trihalomethanes     4.91
Hardness            0.00
Solids              0.00
Conductivity        0.00
Chloramines         0.00
Organic_carbon      0.00
Turbidity           0.00
dtype: float64

In [11]:
sum = df.duplicated().sum()
mean =  df.duplicated().mean() 

print(f"Total duplicate rows: {sum}")
print(f"Percentage of duplicate rows: {mean }%")

Total duplicate rows: 0
Percentage of duplicate rows: 0.0%

In [12]:
print("\n GENERAL INFORMATION")
print("-" * 70)

dimentions = df.shape
rows, columns = df.shape
duplicate_rows = df.duplicated().sum()
duplicate_percentage = duplicate_rows / len(df) * 100

print(f"Dimensions            : {dimentions}")
print(f"Rows                  : {rows:,}")
print(f"Columns               : {columns:,}")
print(f"Duplicate Rows        : {duplicate_rows:,}")
print(f"Duplicate Rows (%)    : {duplicate_percentage:.2f}%")

 GENERAL INFORMATION
----------------------------------------------------------------------
Dimensions            : (3276, 10)
Rows                  : 3,276
Columns               : 10
Duplicate Rows        : 0
Duplicate Rows (%)    : 0.00%

In [13]:

#head of the dataset
#print(f"head of the dataset: {df.head().to_string()}")


#tail of the dataset
#print(f"tail of the dataset: {df.tail().to_string()}")

In [14]:
missing = (
    df.isnull()
      .mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False) 
)
print(missing.to_string())

Sulfate            23.84
ph                 14.99
Trihalomethanes     4.95
Hardness            0.00
Chloramines         0.00
Solids              0.00
Conductivity        0.00
Organic_carbon      0.00
Turbidity           0.00
Potability          0.00

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [22]:
from kika import zInspection

inspection = zInspection(df)

inspection.inspect_data()

======================================================================
                 DATASET INSPECTION REPORT
======================================================================

GENERAL INFORMATION
----------------------------------------------------------------------
Dimensions             : (3276, 10)
Rows                   : 3,276
Columns                : 10
Duplicate Rows         : 0
Duplicate Rows (%)     : 0.00%

COLUMN INFORMATION
----------------------------------------------------------------------
                Data Type  Non-Missing  Missing  Missing %  Duplicate Values %  Duplicated Column
Chloramines       float64         3276        0       0.00                0.00              False
Conductivity      float64         3276        0       0.00                0.00              False
Hardness          float64         3276        0       0.00                0.00              False
Organic_carbon    float64         3276        0       0.00                0.00              False
Potability          int64         3276        0       0.00               99.94              False
Solids            float64         3276        0       0.00                0.00              False
Sulfate           float64         2495      781      23.84               23.81              False
Trihalomethanes   float64         3114      162       4.95                4.91              False
Turbidity         float64         3276        0       0.00                0.00              False
ph                float64         2785      491      14.99               14.96              False

SAMPLE OF THE DATASET
----------------------------------------------------------------------

First 5 rows:
         ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654       10.379783        86.990970   2.963135           0
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359       15.180013        56.329076   4.500656           0
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213       16.868637        66.420093   3.055934           0
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516       18.436524       100.341674   4.628771           0
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813       11.558279        31.997993   4.075075           0

Last 5 rows:
            ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability
3271  4.668102  193.681735  47580.991603     7.166639  359.948574    526.424171       13.894419        66.687695   4.435821           1
3272  7.808856  193.553212  17329.802160     8.061362         NaN    392.449580       19.903225              NaN   2.798243           1
3273  9.419510  175.762646  33155.578218     7.350233         NaN    432.044783       11.039070        69.845400   3.298875           1
3274  5.126763  230.603758  11983.869376     6.303357         NaN    402.883113       11.168946        77.488213   4.708658           1
3275  7.874671  195.102299  17404.177061     7.509306         NaN    327.459760       16.140368        78.698446   2.309149           1

STATISTICAL SUMMARY
----------------------------------------------------------------------
                ph     Hardness        Solids  Chloramines      Sulfate  Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000
mean      7.080795   196.369496  22014.092526     7.122277   333.775777    426.205111       14.284970        66.396293     3.966786     0.390110
std       1.594320    32.879761   8768.570828     1.583085    41.416840     80.824064        3.308162        16.175008     0.780382     0.487849
min       0.000000    47.432000    320.942611     0.352000   129.000000    181.483754        2.200000         0.738000     1.450000     0.000000
25%       6.093092   176.850538  15666.690297     6.127421   307.699498    365.734414       12.065801        55.844536     3.439711     0.000000
50%       7.036752   196.967627  20927.833607     7.130299   333.073546    421.884968       14.218338        66.622485     3.955028     0.000000
75%       8.062066   216.667456  27332.762127     8.114887   359.950170    481.792304       16.557652        77.337473     4.500320     1.000000
max      14.000000   323.124000  61227.196008    13.127000   481.030642    753.342620       28.300000       124.000000     6.739000     1.000000

======================================================================
                  END OF REPORT
======================================================================

In [17]:
# cheking for file existance




if not DATA.exists():
    print("Path does not exist")


if not DATA.is_file():
    print("The path does not point to a file")


if DATA.suffix.lower() != ".csv":
    print("File is not a CSV")


if DATA.stat().st_size == 0:
    print("File is empty")



if df.empty:
    print("Dataset is empty")
else:
    print("Dataset contains data")

Dataset contains data

In [18]:
print(DATA.stat().st_size)

525187

In [19]:
try:
    df = pd.read_csv(DATA)
    print("CSV loaded successfully")
    df.head()

except Exception as e:
    print(f"Failed to read CSV: {e}")

CSV loaded successfully

In [20]:
expected_columns = {
    "ph",
    "Hardness",
    "Solids",
    "Chloramines",
    "Sulfate",
    "Conductivity",
    "Organic_carbon",
    "Trihalomethanes",
    "Turbidity",
    "Potability"
}



actual_columns = set(df.columns)

missing_columns = expected_columns - actual_columns
unexpected_columns = actual_columns - expected_columns

print("Missing:", missing_columns)
print("Unexpected:", unexpected_columns)

Missing: set()
Unexpected: set()